services:
  cgimagegs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NONROOT_USERNAME=ubuntu
        - PROJECT_PATH=/project/cgimagegs
    restart: on-failure
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
